### ISSUE TITLE
Q: can this be used for a generic JDBC driver?

### ISSUE THREAD

**Issue by zrml** [japettyjohn/go-jdbc#3]
Thank you

**Comment by japettyjohn** [comment]
Yes. 

Most thoroughly used with Oracle and Vertica databases. Unit tests however are written for MySQL as that is more available.

**Comment by zrml** [comment]
Thank you @japettyjohn 
So glad I've found you! :)
Hoping to be able to test it in the next month. Cool.

**Comment by zrml** [comment]
closing it :) TX!
