### ISSUE TITLE
unknown driver gojdbc forgotten import

### ISSUE THREAD

**Issue by markskywater** [japettyjohn/go-jdbc#4]
I'm attempting to use go-jdbc to access and Ingres database using iijdbc.jar, but getting the error "sql: unknown driver "gojdbc" (forgotten import?"

Will you provide a usage example?

package main

import (
	"database/sql"
	"log"

	_ "github.com/japettyjohn/go-jdbc"
)

// NewDB establishes a new Ingres JDBC Connection.
// The are no args. NewDB returns *sql.DB.
func NewDB() *sql.DB {
	dbh, err := sql.Open("gojdbc", "jdbc:iijdbc://HOSTNAME:II7/DBNAME;UID=ark;PWD=secretPassword")
	if err != nil {
		log.Fatal("DB connection problem", err)
		//panic(err.Error())
	}
	return dbh
}

// CloseDB closes the database connection.
// The argument is the database handle to close.
func CloseDB(dbhandle *sql.DB) error {
	err := dbhandle.Close()
	return err

}

**Comment by japettyjohn** [comment]
The driver is registered as "jdbc", not "gojdbc". You can see that [here](https://github.com/japettyjohn/go-jdbc/blob/master/driver.go#L69).

**Comment by markskywater** [comment]
Thank you so much. I read line 22 of driver_test.go and completely missed that.

**Comment by japettyjohn** [comment]
Use the URL, if it's ijdbc - https://www.dbschema.com/ingres-jdbc-driver.html.

**Comment by islippers** [comment]
Hi all, i see this questions was closed here. I am also trying to use this repo to connect to ingres. My question is where and how do i specify the JAR file path and the JDBC_DRIVER_CLASS?

I am sure the code would need these setting to connect? 

For now this is what I have.. 
db, err := sql.Open("jdbc", "jdbc:ingres://<host>:<port>/<database>;user=<user>;password=<password>")
	if err != nil {
		log.Fatal("DB connection problem", err)
	}

I do now get and error but when i try and use the db lets say 'err := db.Ping()' I get this error 
dial jdbc: unknown network jdbc 

Pretty sure i am missing something
